### PR TITLE
added DoubleScatter treemaker

### PR DESCRIPTION
**Pull request by berget2**

### CODE REVIEW

**Comment by JelleAalbers** [comment]
Hi Ted, thanks for committing your double scatter treemaker. 
 * Maybe you could add a docstring explaining what the treemaker does and what variables come out?
 * I noticed there is a 'krInt' variable. Is this double scatter treemaker doing anything Krypton (or even Krypton83m) specific, or is it a generic double decay analysis treemaker?

**Comment by berget2** [comment]
Hi Jelle,

Sure I'll add explanations. This is designed to be a generic double decay
treemaker, the krInt variable has been carried over from older versions,
I'll try to remember to rename it when I update.

Thanks!

**Comment by berget2** [comment]
The goal is to find multiple signal events as follows:
*    First S1 (s10) attributed to interactions[0]
*    Additional interaction required for second S1 (s11)
    *    Prioritize 2nd interaction with S1 and S2 distinct from interaction[0]
    *    Otherwise select interaction with S1 distinct from interactions[0] but identical S2
*    interactions re-ordered by S1 hit_time_mean
    Positions (x,y,z) pulled from interactions (e.g. interactions[0].x)

**Comment by JelleAalbers** [comment]
Updated in #36

**Pull request closed without merging**
