### PR TITLE
Update SR2 TensorFlow Net

### PR DESCRIPTION
**Pull request by weiyuehuan**
This run number updating is for the first 2- month of SR2 data.

The corresponding net can be found in the pax PR:
https://github.com/XENON1T/pax/pull/735

### CODE REVIEW

**Comment by feigaodm** [comment]
I'll leave it to @ershockley to check whether the PR is ready.

**Comment by l-althueser** [comment]
Is there a way to know wether this has an impact for certain analyses? Or to phrase it different - should everybody also reload SR0 and SR1 data because it could be different?
This doesn't has to be answered here and now but please keep us updated - Thanks!

**Comment by feigaodm** [comment]
@ershockley So we give up run number 6379?

**Comment by ershockley** [comment]
@l-althueser I think SR0 and SR1 are fine. The runs affected in the SR0-SR1 transition are all earthquake runs so those for sure are fine. The SR1-SR2 transition affects runs that had to be updated anyway. We just need to make sure to always use the gain model to inform these things -- it's also a good double check on the gain model.

**Comment by ershockley** [comment]
@feigaodm it's a bad earthquake run anyway, but according to gain model we'd need another PMT map just for that run right?

**Comment by feigaodm** [comment]
yeah, I understand based on your description, my question is whether will this produce bugs in processing, or anyway another "random" map will be used instead

**Comment by ershockley** [comment]
Ok I see your point. Let's stick it in one of the periods, it will never be used for science data anyway.

**Comment by feigaodm** [comment]
@ershockley Will you make a version_bump in Corrections Minitree version for reprocessing or manually reprocess that period?

**Comment by ershockley** [comment]
@feigaodm if you're okay with it now can you merge?

**Comment by ershockley** [comment]
@feigaodm sorry good timing :) Is the Kr83m electron lifetime model updated as well? If so I think we should do version bump.

**Pull request merged**
