### PR TITLE
New S1 LCE map based on NN 3D FDC

### PR DESCRIPTION
**Pull request by pdeperio**
Update correction for S1 based on https://github.com/XENON1T/pax/pull/628. 

This switches the default ```cs1``` to use NN 3D FDC as proposed in https://github.com/XENON1T/hax/issues/155.  The old TPF 2D FDC ```cs1``` moved to ```cs1_tpf_2dfdc ``` for comparison studies.

Awaiting SR0 map before merging.

(Warning: not tested yet.)

### CODE REVIEW

**Comment by pdeperio** [comment]
@tunnell @feigaodm Why is codacy disabled now?

**Comment by pdeperio** [comment]
then lax should be updated explicitly

**Comment by feigaodm** [comment]
yeah, a change in lax will be good enough. Ideally we should use the 'best' algrithm as the default 'x,y,z' positions and right now it's NN after 3d-FDC. But this can be updated whenever a better one is chozen.

**Comment by pdeperio** [comment]
SR0 LCE map now implemented from https://github.com/XENON1T/pax/pull/631

OK from my side, unless @feigaodm or @coderdj want to make position variable names more explicit or remove ```cs1_tpf_2dfdc``` (i.e. make final decision on ```cs1``` using NN 3D FDC now).

**Pull request merged**
