### PR TITLE
Add posrec minitree for DoubleScatter

### PR DESCRIPTION
**Pull request by ctherreau**
Add posrec minitree for DoubleScatter events:
 - Same things as in the posrec treemaker for Double Scatter = int_a and int_b position 
 - Used Tensor Flow 
 - Requested by Miguel

### CODE REVIEW

**Comment by MAVJ** [comment]
I loaded the minitrees you created at:
 /scratch/midway2/ctherreau/posrec_DoubleS1Scatter_Minitree/pax_v6.8.0 
and it looks good to me!

**Comment by tunnell** [comment]
Flake8 detected 24 issues on da5df67529ea33129a3e56373d2d205c11fbe4f3
Visit https://sider.review/gh/50927571/pull_requests/227 to review the issues.

**Comment by pdeperio** [comment]
Just fixed the ```Sider``` (```flake8```) style issues.

@ctherreau To avoid this in the future, before committing please check style issues with e.g.:

```
flake8 posrec_DoubleScatter.py
```

and fix manually, or automatically (if all issues understood) with:

```
autopep8 -i posrec_DoubleScatter.py
```

**Comment by pdeperio** [comment]
Is it urgent (for production)? Would be nice to develop a refactored long-term solution instead. @tunnell @JelleAalbers any estimate of how long it would take someone to do this?

**Comment by feigaodm** [comment]
no, I don't think it's very urgent. I just thought this has been there for quite some time and people might be waiting for it.

**Comment by MAVJ** [comment]
I would say that it is not urgent at the moment, but it will be important for everything Post-SR1: i.e. to follow up charge accumulation, corrections about inwards reconstruction, e-lifetime and every study that is using/selecting Kr83m data

**Pull request closed without merging**
