### PR TITLE
Unblinding of 0vbb energy region

### PR DESCRIPTION
**Pull request by cwittweg**
Following the decision to unblind the 0vbb data, I removed the respective lines in the code. Please find the link to the unblinding proposal [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:0vbb_unblinding) (@chiaracapelli, @DonNabla, @WolfXeHD).

### CODE REVIEW

**Review by skazama — APPROVED** [review]

**Comment by jpienaar13** [comment]
@cwittweg Did you test this locally to make sure it behaves as expected on a dataset?

**Comment by cwittweg** [comment]
I didn't check it because the removal is very straightforward. If the line for the blinding is not there, the preselection will not be applied. But if you think it is necessary we can of course check.

**Comment by jpienaar13** [comment]
Just check on a single run if you dont mind, so we dont have to merge things twice

**Comment by chiaracapelli** [comment]
Hi, I just tested it locally. HAX is loaded and here a plot of 100 random datasets during SR1, no cuts applied, only a very loose preselection

unblinding_PR

**Comment by jpienaar13** [comment]
Ok. Seems good

**Review by jpienaar13 — APPROVED** [review]

**Comment by cwittweg** [comment]
In any case good that you made us check. I had left in a line that broke this by accident! Lesson learned for the future.

**Pull request merged**
