### PR TITLE
Unblind the DEC region after NG data after SR1

### PR DESCRIPTION
**Pull request by alexfieg**
In order to investigate the I-125 removal further we need to unblind the region between 50 keV and 80 keV in the data past the NG run beyond SR1. We will not use this data anyway for the DEC search as we fixed ourselves to SR1.

### CODE REVIEW

**Comment by pdeperio** [comment]
Add [link to note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:sciencerun0:check_iodine125_removal_in_ambe_data#projection_for_neutron_generator_sensitivity_to_higher_removal_efficiencies)

**Comment by coderdj** [comment]
Can merge. Shingo brought up the valid point that the E lifetime is wrong right now to blinding boxes in incorrect location.

**Comment by feigaodm** [comment]
that's true, but when producing these minitrees in the correction, they should have correctd S1 and S2s in the correct way. I think that will fix this problem.

**Comment by skazama** [comment]
I don't know correct e-lifetime model is already implemented in hax or not. We had a huge e-lifetime drop last month, which is not modelled currently, so I think even if we produce correction minitree by yourself, cs2 is currently wrong.

**Comment by feigaodm** [comment]
By they I mean @alexfieg and @cwittweg :)

**Comment by alexfieg** [comment]
We are aware of this and Michelle and the shifters had a look into this. But we will correct this manually using other lines and the upcoming Kr83m measurement

**Comment by cwittweg** [comment]
But without e-lifetime model we cannot guarantee that the right energy region is unblinded. We should update the model which might be possible even without Kr-83m calibration by using the activated xenon lines during and after the NG run. These are not blind and comparable to Kr-83m. I can look into this once I am back from DPG.

**Comment by cwittweg** [comment]
Okay, the way the blinding cut is defined this should not be an issue, but we should update the e-lifetime model anyhow.

**Comment by feigaodm** [comment]
I think it's safe to keep this data unblinded as this won't be used to search for new physics especially at this energy range. Be careful about the correction and energy re-calibration, otherwise you won't be able to see your expected signal easily.

**Comment by pdeperio** [comment]
Hang on... sorry, I just realized https://github.com/XENON1T/hax/pull/211 might affect you now (PosRec minitrees will not be simply unblinded with this PR, and need to regenerate them...)

**Comment by feigaodm** [comment]
yeah, that might had affect their analysis after AmBe too, right?

**Comment by pdeperio** [comment]
The previous post-AmBe unblinding should be fine, their ```PositionReconstruction``` minitree version is ```1.2```. But latest datasets are ```1.1```, which is bad, please wait while I work with @ershockley to get this fixed.

**Pull request merged**
