### PR TITLE
Added a tqdm toggle

### PR DESCRIPTION
**Pull request by Riciardos**
When I tried to use hax.minitrees.load() multiple times in the same output(I put it in a for loop), the tqdm package would sometimes give an I/O error, causing the loop to end. This is just a small fix that allows you to toggle the tqdm bar on or off. It is on by default (tqdm_on = True) and in a notebook you can change it by running hax.config.update(tqdm_on = False)

### CODE REVIEW

**Comment by Riciardos** [comment]
Here is the traceback for the bug I encountered from tqdm:

```
ValueErrorTraceback (most recent call last)
<ipython-input-11-06fda223e396> in <module>()
     35 
     36     ## Load data and make a cut
---> 37     data = hax.minitrees.load(dataset, treemakers=[SingleChannelTM], force_reload = True)
     38     data_single_channel = data[data['s1_tot_area'] > 15000]
     39 

/home/xws/hax/hax/minitrees.py in load(datasets, treemakers, force_reload)
    151         dataframes = []
    152         for dataset in datasets:
--> 153             minitree_path = get(dataset, treemaker, force_reload=force_reload)
    154             new_df = pd.DataFrame.from_records(root_numpy.root2rec(minitree_path))
    155             dataframes.append(new_df)

/home/xws/hax/hax/minitrees.py in get(dataset, treemaker, force_reload)
    115         # We have to make the minitree file
    116         # This will raise FileNotFoundError if the root file is not found
--> 117         skimmed_data = treemaker().get_data(dataset)
    118         print("Created minitree %s for dataset %s" % (treemaker.__name__, dataset))
    119 

/home/xws/hax/hax/minitrees.py in get_data(self, dataset)
     44         """Return data extracted from running over dataset"""
     45         loop_over_dataset(dataset, self.process_event,
---> 46                           branch_selection=hax.config['basic_branches'] + list(self.extra_branches))
     47         self.check_cache(force_empty=True)
     48         if not hasattr(self, 'data'):

/home/xws/hax/hax/paxroot.py in loop_over_datasets(datasets_names, event_function, branch_selection)
     91         except Exception as e:
     92             rootfile.Close()
---> 93             raise e
     94 
     95 # For backward compatibility

/home/xws/hax/hax/paxroot.py in loop_over_datasets(datasets_names, event_function, branch_selection)
     77         try:
     78             if hax.config['tqdm_on']:
---> 79                 for event_i in tqdm(range(n_events)):
     80                     t.GetEntry(event_i)
     81                     event = t.events

/home/xws/anaconda3/envs/pax/lib/python3.4/site-packages/tqdm-4.5.0-py3.4.egg/tqdm/_tqdm.py in __iter__(self)
    605                              else ncols),
    606                             self.desc, ascii, unit, unit_scale,
--> 607                             1 / avg_time if avg_time else None, bar_format))
    608 
    609                         if self.pos:

/home/xws/anaconda3/envs/pax/lib/python3.4/site-packages/tqdm-4.5.0-py3.4.egg/tqdm/_tqdm.py in print_status(s)
     96         def print_status(s):
     97             len_s = len(s)
---> 98             fp_write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
     99             fp.flush()
    100             last_printed_len[0] = len_s

/home/xws/anaconda3/envs/pax/lib/python3.4/site-packages/tqdm-4.5.0-py3.4.egg/tqdm/_tqdm.py in fp_write(s)
     90 
     91         def fp_write(s):
---> 92             fp.write(_unicode(s))
     93 
     94         last_printed_len = [0]  # closure over mutable variable (fast)

/home/xws/anaconda3/envs/pax/lib/python3.4/site-packages/ipykernel/iostream.py in write(self, string)
    315 
    316             is_child = (not self._is_master_process())
--> 317             self._buffer.write(string)
    318             if is_child:
    319                 # newlines imply flush in subprocesses

ValueError: I/O operation on closed file

```

It's probably because I'm doing something nasty by requesting it in a for loop multiple times. The weird thing is that it seems quite random for how many iterations it will complete before this pops up. Might be something to do with never closing the progress bar properly?

Anyway, the bug has never popped up with tqdm disabled, so this might be a nice little addition in case someone experiences the same problem(although very unlikely).

**Comment by JelleAalbers** [comment]
Thanks Ricardo, I made a few small changes. I don't know if we'll see your bug again (I have no idea what might cause it), but an option to turn off the progress bar can also be useful in the future for automated scripts.

 I'll merge along with other pull requests on the next hax release.

**Comment by Riciardos** [comment]
Ah, I knew there was a neater way of doing it, I couldn't come up with it then. Nicely done!

**Comment by sanderbreur** [comment]
Ty Ricardo, I just hit the same error!

ValueError                                Traceback (most recent call last)
<ipython-input-113-eea3351a78db> in <module>()
      1 # %%capture files_loaded
      2 # run hax and save the output of the print statements with capture
----> 3 data = hax.minitrees.load([run_name for run_name in run_names.values()], ['Basics',LargestPeakProperties_s1,PeaksPerEvent])

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/hax-0.3.3-py3.4.egg/hax/minitrees.py in load(datasets, treemakers, force_reload)
    158         dataframes = []
    159         for dataset in datasets:
--> 160             minitree_path = get(dataset, treemaker, force_reload=force_reload)
    161             new_df = pd.DataFrame.from_records(root_numpy.root2rec(minitree_path))
    162             dataframes.append(new_df)

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/hax-0.3.3-py3.4.egg/hax/minitrees.py in get(run_name, treemaker, force_reload)
    118         # We have to make the minitree file
    119         # This will raise FileNotFoundError if the root file is not found
--> 120         skimmed_data = treemaker().get_data(run_name)
    121         print("Created minitree %s for dataset %s" % (treemaker.__name__, run_name))
    122 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/hax-0.3.3-py3.4.egg/hax/minitrees.py in get_data(self, dataset)
     46         self.run_number = runs.get_run_number(dataset)
     47         loop_over_dataset(dataset, self.process_event,
---> 48                           branch_selection=hax.config['basic_branches'] + list(self.extra_branches))
     49         self.check_cache(force_empty=True)
     50         if not hasattr(self, 'data'):

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/hax-0.3.3-py3.4.egg/hax/paxroot.py in loop_over_datasets(datasets_names, event_function, branch_selection)
    121         a list of branches to read.
    122     """
--> 123     for _ in function_results_datasets(datasets_names, event_function, branch_selection):
    124         # do nothing with the results
    125         pass

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/hax-0.3.3-py3.4.egg/hax/paxroot.py in function_results_datasets(datasets_names, event_function, branch_selection, kwargs)
    108         except Exception as e:
    109             rootfile.Close()
--> 110             raise e
    111 
    112 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/hax-0.3.3-py3.4.egg/hax/paxroot.py in function_results_datasets(datasets_names, event_function, branch_selection, kwargs)
     99             if hax.config.get('tqdm_on', True):
    100                 source = tqdm(source)
--> 101             for event_i in source:
    102                 t.GetEntry(event_i)
    103                 event = t.events

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/tqdm-3.8.0-py3.4.egg/tqdm/_tqdm.py in __iter__(self)
    481                              else ncols),
    482                             self.desc, ascii, unit, unit_scale,
--> 483                             1 / avg_time if avg_time else None, bar_format))
    484 
    485                         # If no `miniters` was specified, adjust automatically

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/tqdm-3.8.0-py3.4.egg/tqdm/_tqdm.py in print_status(s)
     93         def print_status(s):
     94             len_s = len(s)
---> 95             fp.write('\r' + s + (' ' * max(last_printed_len[0] - len_s, 0)))
     96             fp.flush()
     97             last_printed_len[0] = len_s

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/colorama/ansitowin32.py in write(self, text)
     38 
     39     def write(self, text):
---> 40         self.__convertor.write(text)
     41 
     42 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/colorama/ansitowin32.py in write(self, text)
    139     def write(self, text):
    140         if self.strip or self.convert:
--> 141             self.write_and_convert(text)
    142         else:
    143             self.wrapped.write(text)

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/colorama/ansitowin32.py in write_and_convert(self, text)
    167             self.convert_ansi(*match.groups())
    168             cursor = end
--> 169         self.write_plain_text(text, cursor, len(text))
    170 
    171 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/colorama/ansitowin32.py in write_plain_text(self, text, start, end)
    172     def write_plain_text(self, text, start, end):
    173         if start < end:
--> 174             self.wrapped.write(text[start:end])
    175             self.wrapped.flush()
    176 

/project/lgrandi/anaconda3/envs/pax_head/lib/python3.4/site-packages/ipykernel/iostream.py in write(self, string)
    315 
    316             is_child = (not self._is_master_process())
--> 317             self._buffer.write(string)
    318             if is_child:
    319                 # newlines imply flush in subprocesses

ValueError: I/O operation on closed file

**Comment by Riciardos** [comment]
Luckily I wasn't the only one! Which means I helped! Yay!

**Pull request merged**
